//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class R_Cwiczenia : Abstrakcyjny_Rozkaz
{
    public virtual string DocelowaBaza
    {
        get;
        set;
    }

    public R_Cwiczenia(Action<string> Callback)
	{
        ID = 1;
        this.Callback = Callback;
    }

    public virtual void Ustaw_Baze_Docelowa(string Baza_Docelowa)
    {
        this.DocelowaBaza = Baza_Docelowa;
    }

}

