//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class R_Produkuj : Abstrakcyjny_Rozkaz
{
    public virtual string DocelowaBaza
    {
        get;
        set;
    }

    public virtual string ParametryProduktu
    {
        get;
        set;
    }

    public virtual Action<Abstrakcyjny_Rozkaz> CentralaZlecWykonanieRozkazu
    {
        get;
        set;
    }

    public virtual Func<string,Abstrakcyjny_Rozkaz> CentralaWytworzRozkaz
    {
        get;
        set;
    }

	public R_Produkuj(Action<string> Callback)
    {
        ID = 4;
        this.Callback = Callback;
    }

    public virtual void Ustaw_Parametry_Rozkazu(string ParametryProduktu, string DocelowaBaza, Action<Abstrakcyjny_Rozkaz> CentralaZlecWykonanieRozkazu, Func<string, Abstrakcyjny_Rozkaz> CentralaWytworzRozkaz)
    {
        this.ParametryProduktu = ParametryProduktu;
        this.CentralaWytworzRozkaz = CentralaWytworzRozkaz;
        this.CentralaZlecWykonanieRozkazu = CentralaZlecWykonanieRozkazu;
        this.DocelowaBaza = DocelowaBaza;
    }

}

