//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Centrala
{
	public virtual Abstrakcyjna_Jednostka straznik_listy_jednostek
	{
		get;
		set;
	}

	public virtual IEnumerable<Abstrakcyjna_Fabryka_Rozkazow> Lista_Fabryk_Rozkazow
	{
		get;
		set;
	}

	public virtual void Dodaj(Abstrakcyjna_Jednostka Jednostka_Do_Dodania)
	{
		throw new System.NotImplementedException();
	}

	public Centrala()
	{
	}

	public virtual void WydajRozkaz(string Tekst_Rozkazu)
	{
		throw new System.NotImplementedException();
	}

	public virtual string Lista_Dostepnych_Rozkazow()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Odczytaj_Raport(string Raport)
	{
		throw new System.NotImplementedException();
	}

	public virtual Abstrakcyjny_Rozkaz Wytworz_rozkaz(string Tekst_Rozkazu)
	{
		throw new System.NotImplementedException();
	}

	public virtual Abstrakcyjny_Rozkaz Wytworz_rozkaz_zlecony_przez_jednostke(string Tekst_Rozkazu)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Zlec_Wykonanie_Rozkazu_Jednostkom(Abstrakcyjny_Rozkaz rozkaz)
	{
		throw new System.NotImplementedException();
	}

}

