//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class F_Karabin : Fabryka
{
	public override void Wykonaj(Abstrakcyjny_Rozkaz rozkaz)
	{
		throw new System.NotImplementedException();
	}

	protected virtual Zasob_wojskowy ProdukujKarabin(string Parametry_Karabinu)
	{
		throw new System.NotImplementedException();
	}

}

