//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class P_Zolnierz : Poligon
{
	public override void Wykonaj(Abstrakcyjny_Rozkaz rozkaz)
	{
		throw new System.NotImplementedException();
	}

	protected virtual Zasob_wojskowy MobilizujZolnierza(string Parametry_Zolnierza)
	{
		throw new System.NotImplementedException();
	}

}

