//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class R_DodajZasobWojskowy : Abstrakcyjny_Rozkaz
{
	public virtual Zasob_wojskowy Zasob_Do_Dodania
	{
		get;
		set;
	}

	public virtual string DocelowaBaza
	{
		get;
		set;
	}

	public R_DodajZasobWojskowy(string DocelowaBaza, Zasob_wojskowy Zasob_Do_Dodania)
	{
	}

}

