//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class B_Warszawa : Baza
{

    public B_Warszawa()
    {
        Nazwa_Bazy = "Warszawa";
        Lista_Rozkazow.Add(1);
        Lista_Rozkazow.Add(2); //komentarz
    }
}

