//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class B_Wroclaw : Baza
{
    public B_Wroclaw()
    {
        ListaZasobow = new List<Zasob_wojskowy>();

        Nazwa_Bazy = "Wroclaw";
        Lista_Rozkazow.Add(1); //Rozkaz Cwiczenia
        Lista_Rozkazow.Add(2); //Razkaz Dodaj Zasob Wojskowy 
    }
}

