//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Baza : Abstrakcyjna_Jednostka
{
    public virtual string Nazwa_Bazy
    {
        get;
        set;
    }
    public virtual List<Zasob_wojskowy> ListaZasobow
	{
		get;
		set;
	}

    public override void Wykonaj(Abstrakcyjny_Rozkaz rozkaz)
    {
        if(this.CzyWokonac(rozkaz))
        {
            if(rozkaz.ID == 2) // Dodanie Jednostki do bazy
            {
                R_DodajZasobWojskowy RozkazZrzutowany = (R_DodajZasobWojskowy)rozkaz;
                if(RozkazZrzutowany.DocelowaBaza == Nazwa_Bazy)
                {
                    ListaZasobow.Add(RozkazZrzutowany.Zasob_Do_Dodania);
                    rozkaz.Raportuj(String.Format("{0} dodano {1}", Nazwa_Bazy, RozkazZrzutowany.Zasob_Do_Dodania.Nazwa));
                }
                else
                {
                    this.NastepnikWykonaj(rozkaz);
                }
            }
        }
        else
        {
            this.NastepnikWykonaj(rozkaz);
        }
    }

}

