//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Poligon : Abstrakcyjna_Jednostka
{
    public Poligon()
    {
        Lista_Rozkazow = new List<int>();
        Lista_Rozkazow.Add(3); //Rozkaz Mobilizuj
        Lista_Rozkazow.Add(5); // Rozkaz Zamelduj
    }

    public override void Wykonaj(Abstrakcyjny_Rozkaz rozkaz)
    {
        this.NastepnikWykonaj(rozkaz);
    }
}

