//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FR_DodajZasobWojskowy : Abstrakcyjna_Fabryka_Rozkazow
{
	public override Abstrakcyjny_Rozkaz TworzRozkaz(string ParametryRozkazu, Centrala info)
	{
        R_DodajZasobWojskowy rozkaz = new R_DodajZasobWojskowy(info.Odczytaj_Raport);

        return rozkaz;
	}

	public FR_DodajZasobWojskowy()
	{
        nazwa_rozkazu = "dodajzasob";
    }
}

