//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FR_Mobilizacja : Abstrakcyjna_Fabryka_Rozkazow
{
	public override Abstrakcyjny_Rozkaz TworzRozkaz(string ParametryRozkazu, Centrala info)
	{
        string[] Parametry = ParametryRozkazu.Split('|');
        R_Mobilizacja Nowy_Rozkaz = new R_Mobilizacja(info.Odczytaj_Raport);

        Nowy_Rozkaz.Ustaw_Parametry_Rozkazu(String.Join("|", Parametry.Skip(2).ToArray()), Parametry[1], info.ZlecWykonanieRozkazu, info.Wytworz_rozkaz);
        return Nowy_Rozkaz;
    }

	public FR_Mobilizacja()
	{
        nazwa_rozkazu = "mobiliza";
    }

}

