//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FR_Produkuj : Abstrakcyjna_Fabryka_Rozkazow
{
    public override Abstrakcyjny_Rozkaz TworzRozkaz(string ParametryRozkazu, Centrala info)
	{
        string[] Parametry = ParametryRozkazu.Split('|');
        R_Produkuj Nowy_Rozkaz = new R_Produkuj(info.Odczytaj_Raport);

        Nowy_Rozkaz.Ustaw_Parametry_Rozkazu(String.Join("|", Parametry.Skip(2).ToArray()), Parametry[1], info.Zlec_Wykonanie_Rozkazu_Jednostkom, info.Wytworz_rozkaz_zlecony_przez_jednostke);
        return Nowy_Rozkaz;
    }

	public FR_Produkuj()
	{
        nazwa_rozkazu = "produkuj";
        Wydawany_Tylko_Przez_Jednostki = false;
    }

    public override string PodajFormuleRozkazu()
    {
        return "produkuj|nazwa_bazy_docelowej|typ_obiektu_wojskowego_do_produkcji\n";
    }

}

