//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FR_Zamelduj : Abstrakcyjna_Fabryka_Rozkazow
{
	public override Abstrakcyjny_Rozkaz TworzRozkaz(string parametr, Centrala info)
	{
        return new R_Zamelduj(info.Odczytaj_Raport);
	}

	public FR_Zamelduj()
	{
        nazwa_rozkazu = "zamelduj";
        Wydawany_Tylko_Przez_Jednostki = false;
    }

	public override string PodajFormuleRozkazu()
	{
        return "zamelduj\n";
    }

}

